#pragma once

#define COMMON_LINE_COUNT 5
#define PULL_STRAIGHT_RATE 1.3
#define PULL_START_RATE 4
#define PULL_START_ANGLE_MIN 85
#define PULL_START_ANGLE_MAX 130
#define PULL_START_HEIGHT_BETWEEN_SHOULDER_AND_ELBOW 20

#define PIXEL_DIFFER_THRESHOLD 20
#define SYMM_COUNT_THRESHOLD 5

#define SIT_FRAME_COUNT 4

